// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockCrushRegistrar is an autogenerated mock type for the CrushRegistrar type
type MockCrushRegistrar struct {
	mock.Mock
}

type MockCrushRegistrar_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCrushRegistrar) EXPECT() *MockCrushRegistrar_Expecter {
	return &MockCrushRegistrar_Expecter{mock: &_m.Mock}
}

// RegisterCrush provides a mock function with given fields: ctx, userID, crushName, crushBirthday, confirmUnmatch
func (_m *MockCrushRegistrar) RegisterCrush(ctx context.Context, userID string, crushName string, crushBirthday string, confirmUnmatch bool) (bool, bool, error) {
	ret := _m.Called(ctx, userID, crushName, crushBirthday, confirmUnmatch)

	if len(ret) == 0 {
		panic("no return value specified for RegisterCrush")
	}

	var r0 bool
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, bool) (bool, bool, error)); ok {
		return rf(ctx, userID, crushName, crushBirthday, confirmUnmatch)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, bool) bool); ok {
		r0 = rf(ctx, userID, crushName, crushBirthday, confirmUnmatch)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, bool) bool); ok {
		r1 = rf(ctx, userID, crushName, crushBirthday, confirmUnmatch)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, string, bool) error); ok {
		r2 = rf(ctx, userID, crushName, crushBirthday, confirmUnmatch)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockCrushRegistrar_RegisterCrush_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterCrush'
type MockCrushRegistrar_RegisterCrush_Call struct {
	*mock.Call
}

// RegisterCrush is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - crushName string
//   - crushBirthday string
//   - confirmUnmatch bool
func (_e *MockCrushRegistrar_Expecter) RegisterCrush(ctx interface{}, userID interface{}, crushName interface{}, crushBirthday interface{}, confirmUnmatch interface{}) *MockCrushRegistrar_RegisterCrush_Call {
	return &MockCrushRegistrar_RegisterCrush_Call{Call: _e.mock.On("RegisterCrush", ctx, userID, crushName, crushBirthday, confirmUnmatch)}
}

func (_c *MockCrushRegistrar_RegisterCrush_Call) Run(run func(ctx context.Context, userID string, crushName string, crushBirthday string, confirmUnmatch bool)) *MockCrushRegistrar_RegisterCrush_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(bool))
	})
	return _c
}

func (_c *MockCrushRegistrar_RegisterCrush_Call) Return(matched bool, isFirstCrushRegistration bool, err error) *MockCrushRegistrar_RegisterCrush_Call {
	_c.Call.Return(matched, isFirstCrushRegistration, err)
	return _c
}

func (_c *MockCrushRegistrar_RegisterCrush_Call) RunAndReturn(run func(context.Context, string, string, string, bool) (bool, bool, error)) *MockCrushRegistrar_RegisterCrush_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCrushRegistrar creates a new instance of MockCrushRegistrar. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCrushRegistrar(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCrushRegistrar {
	mock := &MockCrushRegistrar{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
