// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	messaging_api "github.com/line/line-bot-sdk-go/v8/linebot/messaging_api"
	mock "github.com/stretchr/testify/mock"
)

// MockLINEReplier is an autogenerated mock type for the LINEReplier type
type MockLINEReplier struct {
	mock.Mock
}

type MockLINEReplier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLINEReplier) EXPECT() *MockLINEReplier_Expecter {
	return &MockLINEReplier_Expecter{mock: &_m.Mock}
}

// ReplyMessage provides a mock function with given fields: request
func (_m *MockLINEReplier) ReplyMessage(request *messaging_api.ReplyMessageRequest) (*messaging_api.ReplyMessageResponse, error) {
	ret := _m.Called(request)

	if len(ret) == 0 {
		panic("no return value specified for ReplyMessage")
	}

	var r0 *messaging_api.ReplyMessageResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*messaging_api.ReplyMessageRequest) (*messaging_api.ReplyMessageResponse, error)); ok {
		return rf(request)
	}
	if rf, ok := ret.Get(0).(func(*messaging_api.ReplyMessageRequest) *messaging_api.ReplyMessageResponse); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*messaging_api.ReplyMessageResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*messaging_api.ReplyMessageRequest) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLINEReplier_ReplyMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplyMessage'
type MockLINEReplier_ReplyMessage_Call struct {
	*mock.Call
}

// ReplyMessage is a helper method to define mock.On call
//   - request *messaging_api.ReplyMessageRequest
func (_e *MockLINEReplier_Expecter) ReplyMessage(request interface{}) *MockLINEReplier_ReplyMessage_Call {
	return &MockLINEReplier_ReplyMessage_Call{Call: _e.mock.On("ReplyMessage", request)}
}

func (_c *MockLINEReplier_ReplyMessage_Call) Run(run func(request *messaging_api.ReplyMessageRequest)) *MockLINEReplier_ReplyMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*messaging_api.ReplyMessageRequest))
	})
	return _c
}

func (_c *MockLINEReplier_ReplyMessage_Call) Return(_a0 *messaging_api.ReplyMessageResponse, _a1 error) *MockLINEReplier_ReplyMessage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLINEReplier_ReplyMessage_Call) RunAndReturn(run func(*messaging_api.ReplyMessageRequest) (*messaging_api.ReplyMessageResponse, error)) *MockLINEReplier_ReplyMessage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLINEReplier creates a new instance of MockLINEReplier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLINEReplier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLINEReplier {
	mock := &MockLINEReplier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
