// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockUserRegistrar is an autogenerated mock type for the UserRegistrar type
type MockUserRegistrar struct {
	mock.Mock
}

type MockUserRegistrar_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRegistrar) EXPECT() *MockUserRegistrar_Expecter {
	return &MockUserRegistrar_Expecter{mock: &_m.Mock}
}

// RegisterUser provides a mock function with given fields: ctx, userID, name, birthday, confirmUnmatch
func (_m *MockUserRegistrar) RegisterUser(ctx context.Context, userID string, name string, birthday string, confirmUnmatch bool) (bool, error) {
	ret := _m.Called(ctx, userID, name, birthday, confirmUnmatch)

	if len(ret) == 0 {
		panic("no return value specified for RegisterUser")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, bool) (bool, error)); ok {
		return rf(ctx, userID, name, birthday, confirmUnmatch)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, bool) bool); ok {
		r0 = rf(ctx, userID, name, birthday, confirmUnmatch)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, bool) error); ok {
		r1 = rf(ctx, userID, name, birthday, confirmUnmatch)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRegistrar_RegisterUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterUser'
type MockUserRegistrar_RegisterUser_Call struct {
	*mock.Call
}

// RegisterUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - name string
//   - birthday string
//   - confirmUnmatch bool
func (_e *MockUserRegistrar_Expecter) RegisterUser(ctx interface{}, userID interface{}, name interface{}, birthday interface{}, confirmUnmatch interface{}) *MockUserRegistrar_RegisterUser_Call {
	return &MockUserRegistrar_RegisterUser_Call{Call: _e.mock.On("RegisterUser", ctx, userID, name, birthday, confirmUnmatch)}
}

func (_c *MockUserRegistrar_RegisterUser_Call) Run(run func(ctx context.Context, userID string, name string, birthday string, confirmUnmatch bool)) *MockUserRegistrar_RegisterUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(bool))
	})
	return _c
}

func (_c *MockUserRegistrar_RegisterUser_Call) Return(isFirstRegistration bool, err error) *MockUserRegistrar_RegisterUser_Call {
	_c.Call.Return(isFirstRegistration, err)
	return _c
}

func (_c *MockUserRegistrar_RegisterUser_Call) RunAndReturn(run func(context.Context, string, string, string, bool) (bool, error)) *MockUserRegistrar_RegisterUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRegistrar creates a new instance of MockUserRegistrar. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRegistrar(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRegistrar {
	mock := &MockUserRegistrar{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
