// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockWebhookUserService is an autogenerated mock type for the WebhookUserService type
type MockWebhookUserService struct {
	mock.Mock
}

type MockWebhookUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWebhookUserService) EXPECT() *MockWebhookUserService_Expecter {
	return &MockWebhookUserService_Expecter{mock: &_m.Mock}
}

// ProcessFollowEvent provides a mock function with given fields: ctx, replyToken
func (_m *MockWebhookUserService) ProcessFollowEvent(ctx context.Context, replyToken string) error {
	ret := _m.Called(ctx, replyToken)

	if len(ret) == 0 {
		panic("no return value specified for ProcessFollowEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, replyToken)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWebhookUserService_ProcessFollowEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessFollowEvent'
type MockWebhookUserService_ProcessFollowEvent_Call struct {
	*mock.Call
}

// ProcessFollowEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - replyToken string
func (_e *MockWebhookUserService_Expecter) ProcessFollowEvent(ctx interface{}, replyToken interface{}) *MockWebhookUserService_ProcessFollowEvent_Call {
	return &MockWebhookUserService_ProcessFollowEvent_Call{Call: _e.mock.On("ProcessFollowEvent", ctx, replyToken)}
}

func (_c *MockWebhookUserService_ProcessFollowEvent_Call) Run(run func(ctx context.Context, replyToken string)) *MockWebhookUserService_ProcessFollowEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockWebhookUserService_ProcessFollowEvent_Call) Return(_a0 error) *MockWebhookUserService_ProcessFollowEvent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWebhookUserService_ProcessFollowEvent_Call) RunAndReturn(run func(context.Context, string) error) *MockWebhookUserService_ProcessFollowEvent_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessJoinEvent provides a mock function with given fields: ctx, replyToken
func (_m *MockWebhookUserService) ProcessJoinEvent(ctx context.Context, replyToken string) error {
	ret := _m.Called(ctx, replyToken)

	if len(ret) == 0 {
		panic("no return value specified for ProcessJoinEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, replyToken)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWebhookUserService_ProcessJoinEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessJoinEvent'
type MockWebhookUserService_ProcessJoinEvent_Call struct {
	*mock.Call
}

// ProcessJoinEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - replyToken string
func (_e *MockWebhookUserService_Expecter) ProcessJoinEvent(ctx interface{}, replyToken interface{}) *MockWebhookUserService_ProcessJoinEvent_Call {
	return &MockWebhookUserService_ProcessJoinEvent_Call{Call: _e.mock.On("ProcessJoinEvent", ctx, replyToken)}
}

func (_c *MockWebhookUserService_ProcessJoinEvent_Call) Run(run func(ctx context.Context, replyToken string)) *MockWebhookUserService_ProcessJoinEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockWebhookUserService_ProcessJoinEvent_Call) Return(_a0 error) *MockWebhookUserService_ProcessJoinEvent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWebhookUserService_ProcessJoinEvent_Call) RunAndReturn(run func(context.Context, string) error) *MockWebhookUserService_ProcessJoinEvent_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessTextMessage provides a mock function with given fields: ctx, userID
func (_m *MockWebhookUserService) ProcessTextMessage(ctx context.Context, userID string) (string, string, string, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ProcessTextMessage")
	}

	var r0 string
	var r1 string
	var r2 string
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, string, string, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) string); ok {
		r2 = rf(ctx, userID)
	} else {
		r2 = ret.Get(2).(string)
	}

	if rf, ok := ret.Get(3).(func(context.Context, string) error); ok {
		r3 = rf(ctx, userID)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// MockWebhookUserService_ProcessTextMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessTextMessage'
type MockWebhookUserService_ProcessTextMessage_Call struct {
	*mock.Call
}

// ProcessTextMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockWebhookUserService_Expecter) ProcessTextMessage(ctx interface{}, userID interface{}) *MockWebhookUserService_ProcessTextMessage_Call {
	return &MockWebhookUserService_ProcessTextMessage_Call{Call: _e.mock.On("ProcessTextMessage", ctx, userID)}
}

func (_c *MockWebhookUserService_ProcessTextMessage_Call) Run(run func(ctx context.Context, userID string)) *MockWebhookUserService_ProcessTextMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockWebhookUserService_ProcessTextMessage_Call) Return(replyText string, quickReplyURL string, quickReplyLabel string, err error) *MockWebhookUserService_ProcessTextMessage_Call {
	_c.Call.Return(replyText, quickReplyURL, quickReplyLabel, err)
	return _c
}

func (_c *MockWebhookUserService_ProcessTextMessage_Call) RunAndReturn(run func(context.Context, string) (string, string, string, error)) *MockWebhookUserService_ProcessTextMessage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWebhookUserService creates a new instance of MockWebhookUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWebhookUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWebhookUserService {
	mock := &MockWebhookUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
