// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/morinonusi421/cupid/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, user
func (_m *MockUserRepository) Create(ctx context.Context, user *model.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - user *model.User
func (_e *MockUserRepository_Expecter) Create(ctx interface{}, user interface{}) *MockUserRepository_Create_Call {
	return &MockUserRepository_Create_Call{Call: _e.mock.On("Create", ctx, user)}
}

func (_c *MockUserRepository_Create_Call) Run(run func(ctx context.Context, user *model.User)) *MockUserRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.User))
	})
	return _c
}

func (_c *MockUserRepository_Create_Call) Return(_a0 error) *MockUserRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_Create_Call) RunAndReturn(run func(context.Context, *model.User) error) *MockUserRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByLineID provides a mock function with given fields: ctx, lineID
func (_m *MockUserRepository) FindByLineID(ctx context.Context, lineID string) (*model.User, error) {
	ret := _m.Called(ctx, lineID)

	if len(ret) == 0 {
		panic("no return value specified for FindByLineID")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.User, error)); ok {
		return rf(ctx, lineID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.User); ok {
		r0 = rf(ctx, lineID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, lineID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_FindByLineID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByLineID'
type MockUserRepository_FindByLineID_Call struct {
	*mock.Call
}

// FindByLineID is a helper method to define mock.On call
//   - ctx context.Context
//   - lineID string
func (_e *MockUserRepository_Expecter) FindByLineID(ctx interface{}, lineID interface{}) *MockUserRepository_FindByLineID_Call {
	return &MockUserRepository_FindByLineID_Call{Call: _e.mock.On("FindByLineID", ctx, lineID)}
}

func (_c *MockUserRepository_FindByLineID_Call) Run(run func(ctx context.Context, lineID string)) *MockUserRepository_FindByLineID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserRepository_FindByLineID_Call) Return(_a0 *model.User, _a1 error) *MockUserRepository_FindByLineID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_FindByLineID_Call) RunAndReturn(run func(context.Context, string) (*model.User, error)) *MockUserRepository_FindByLineID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByNameAndBirthday provides a mock function with given fields: ctx, name, birthday
func (_m *MockUserRepository) FindByNameAndBirthday(ctx context.Context, name string, birthday string) (*model.User, error) {
	ret := _m.Called(ctx, name, birthday)

	if len(ret) == 0 {
		panic("no return value specified for FindByNameAndBirthday")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.User, error)); ok {
		return rf(ctx, name, birthday)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.User); ok {
		r0 = rf(ctx, name, birthday)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, name, birthday)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_FindByNameAndBirthday_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByNameAndBirthday'
type MockUserRepository_FindByNameAndBirthday_Call struct {
	*mock.Call
}

// FindByNameAndBirthday is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - birthday string
func (_e *MockUserRepository_Expecter) FindByNameAndBirthday(ctx interface{}, name interface{}, birthday interface{}) *MockUserRepository_FindByNameAndBirthday_Call {
	return &MockUserRepository_FindByNameAndBirthday_Call{Call: _e.mock.On("FindByNameAndBirthday", ctx, name, birthday)}
}

func (_c *MockUserRepository_FindByNameAndBirthday_Call) Run(run func(ctx context.Context, name string, birthday string)) *MockUserRepository_FindByNameAndBirthday_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockUserRepository_FindByNameAndBirthday_Call) Return(_a0 *model.User, _a1 error) *MockUserRepository_FindByNameAndBirthday_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_FindByNameAndBirthday_Call) RunAndReturn(run func(context.Context, string, string) (*model.User, error)) *MockUserRepository_FindByNameAndBirthday_Call {
	_c.Call.Return(run)
	return _c
}

// FindMatchingUser provides a mock function with given fields: ctx, currentUser
func (_m *MockUserRepository) FindMatchingUser(ctx context.Context, currentUser *model.User) (*model.User, error) {
	ret := _m.Called(ctx, currentUser)

	if len(ret) == 0 {
		panic("no return value specified for FindMatchingUser")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.User) (*model.User, error)); ok {
		return rf(ctx, currentUser)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.User) *model.User); ok {
		r0 = rf(ctx, currentUser)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.User) error); ok {
		r1 = rf(ctx, currentUser)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_FindMatchingUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindMatchingUser'
type MockUserRepository_FindMatchingUser_Call struct {
	*mock.Call
}

// FindMatchingUser is a helper method to define mock.On call
//   - ctx context.Context
//   - currentUser *model.User
func (_e *MockUserRepository_Expecter) FindMatchingUser(ctx interface{}, currentUser interface{}) *MockUserRepository_FindMatchingUser_Call {
	return &MockUserRepository_FindMatchingUser_Call{Call: _e.mock.On("FindMatchingUser", ctx, currentUser)}
}

func (_c *MockUserRepository_FindMatchingUser_Call) Run(run func(ctx context.Context, currentUser *model.User)) *MockUserRepository_FindMatchingUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.User))
	})
	return _c
}

func (_c *MockUserRepository_FindMatchingUser_Call) Return(_a0 *model.User, _a1 error) *MockUserRepository_FindMatchingUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_FindMatchingUser_Call) RunAndReturn(run func(context.Context, *model.User) (*model.User, error)) *MockUserRepository_FindMatchingUser_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, user
func (_m *MockUserRepository) Update(ctx context.Context, user *model.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUserRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - user *model.User
func (_e *MockUserRepository_Expecter) Update(ctx interface{}, user interface{}) *MockUserRepository_Update_Call {
	return &MockUserRepository_Update_Call{Call: _e.mock.On("Update", ctx, user)}
}

func (_c *MockUserRepository_Update_Call) Run(run func(ctx context.Context, user *model.User)) *MockUserRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.User))
	})
	return _c
}

func (_c *MockUserRepository_Update_Call) Return(_a0 error) *MockUserRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_Update_Call) RunAndReturn(run func(context.Context, *model.User) error) *MockUserRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
