// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entities

var TableNames = struct {
	Likes            string
	SchemaMigrations string
	Users            string
}{
	Likes:            "likes",
	SchemaMigrations: "schema_migrations",
	Users:            "users",
}
