// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockVerifier is an autogenerated mock type for the Verifier type
type MockVerifier struct {
	mock.Mock
}

type MockVerifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVerifier) EXPECT() *MockVerifier_Expecter {
	return &MockVerifier_Expecter{mock: &_m.Mock}
}

// VerifyAccessToken provides a mock function with given fields: accessToken
func (_m *MockVerifier) VerifyAccessToken(accessToken string) (string, error) {
	ret := _m.Called(accessToken)

	if len(ret) == 0 {
		panic("no return value specified for VerifyAccessToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(accessToken)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(accessToken)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(accessToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVerifier_VerifyAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyAccessToken'
type MockVerifier_VerifyAccessToken_Call struct {
	*mock.Call
}

// VerifyAccessToken is a helper method to define mock.On call
//   - accessToken string
func (_e *MockVerifier_Expecter) VerifyAccessToken(accessToken interface{}) *MockVerifier_VerifyAccessToken_Call {
	return &MockVerifier_VerifyAccessToken_Call{Call: _e.mock.On("VerifyAccessToken", accessToken)}
}

func (_c *MockVerifier_VerifyAccessToken_Call) Run(run func(accessToken string)) *MockVerifier_VerifyAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockVerifier_VerifyAccessToken_Call) Return(_a0 string, _a1 error) *MockVerifier_VerifyAccessToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVerifier_VerifyAccessToken_Call) RunAndReturn(run func(string) (string, error)) *MockVerifier_VerifyAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyIDToken provides a mock function with given fields: idToken
func (_m *MockVerifier) VerifyIDToken(idToken string) (string, error) {
	ret := _m.Called(idToken)

	if len(ret) == 0 {
		panic("no return value specified for VerifyIDToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(idToken)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(idToken)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(idToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVerifier_VerifyIDToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyIDToken'
type MockVerifier_VerifyIDToken_Call struct {
	*mock.Call
}

// VerifyIDToken is a helper method to define mock.On call
//   - idToken string
func (_e *MockVerifier_Expecter) VerifyIDToken(idToken interface{}) *MockVerifier_VerifyIDToken_Call {
	return &MockVerifier_VerifyIDToken_Call{Call: _e.mock.On("VerifyIDToken", idToken)}
}

func (_c *MockVerifier_VerifyIDToken_Call) Run(run func(idToken string)) *MockVerifier_VerifyIDToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockVerifier_VerifyIDToken_Call) Return(_a0 string, _a1 error) *MockVerifier_VerifyIDToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVerifier_VerifyIDToken_Call) RunAndReturn(run func(string) (string, error)) *MockVerifier_VerifyIDToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVerifier creates a new instance of MockVerifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVerifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVerifier {
	mock := &MockVerifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
