// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	messaging_api "github.com/line/line-bot-sdk-go/v8/linebot/messaging_api"
	mock "github.com/stretchr/testify/mock"
)

// MockLINEMessenger is an autogenerated mock type for the LINEMessenger type
type MockLINEMessenger struct {
	mock.Mock
}

type MockLINEMessenger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLINEMessenger) EXPECT() *MockLINEMessenger_Expecter {
	return &MockLINEMessenger_Expecter{mock: &_m.Mock}
}

// PushMessage provides a mock function with given fields: request
func (_m *MockLINEMessenger) PushMessage(request *messaging_api.PushMessageRequest) (*messaging_api.PushMessageResponse, error) {
	ret := _m.Called(request)

	if len(ret) == 0 {
		panic("no return value specified for PushMessage")
	}

	var r0 *messaging_api.PushMessageResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*messaging_api.PushMessageRequest) (*messaging_api.PushMessageResponse, error)); ok {
		return rf(request)
	}
	if rf, ok := ret.Get(0).(func(*messaging_api.PushMessageRequest) *messaging_api.PushMessageResponse); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*messaging_api.PushMessageResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*messaging_api.PushMessageRequest) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLINEMessenger_PushMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PushMessage'
type MockLINEMessenger_PushMessage_Call struct {
	*mock.Call
}

// PushMessage is a helper method to define mock.On call
//   - request *messaging_api.PushMessageRequest
func (_e *MockLINEMessenger_Expecter) PushMessage(request interface{}) *MockLINEMessenger_PushMessage_Call {
	return &MockLINEMessenger_PushMessage_Call{Call: _e.mock.On("PushMessage", request)}
}

func (_c *MockLINEMessenger_PushMessage_Call) Run(run func(request *messaging_api.PushMessageRequest)) *MockLINEMessenger_PushMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*messaging_api.PushMessageRequest))
	})
	return _c
}

func (_c *MockLINEMessenger_PushMessage_Call) Return(_a0 *messaging_api.PushMessageResponse, _a1 error) *MockLINEMessenger_PushMessage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLINEMessenger_PushMessage_Call) RunAndReturn(run func(*messaging_api.PushMessageRequest) (*messaging_api.PushMessageResponse, error)) *MockLINEMessenger_PushMessage_Call {
	_c.Call.Return(run)
	return _c
}

// ReplyMessage provides a mock function with given fields: request
func (_m *MockLINEMessenger) ReplyMessage(request *messaging_api.ReplyMessageRequest) (*messaging_api.ReplyMessageResponse, error) {
	ret := _m.Called(request)

	if len(ret) == 0 {
		panic("no return value specified for ReplyMessage")
	}

	var r0 *messaging_api.ReplyMessageResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*messaging_api.ReplyMessageRequest) (*messaging_api.ReplyMessageResponse, error)); ok {
		return rf(request)
	}
	if rf, ok := ret.Get(0).(func(*messaging_api.ReplyMessageRequest) *messaging_api.ReplyMessageResponse); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*messaging_api.ReplyMessageResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*messaging_api.ReplyMessageRequest) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLINEMessenger_ReplyMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplyMessage'
type MockLINEMessenger_ReplyMessage_Call struct {
	*mock.Call
}

// ReplyMessage is a helper method to define mock.On call
//   - request *messaging_api.ReplyMessageRequest
func (_e *MockLINEMessenger_Expecter) ReplyMessage(request interface{}) *MockLINEMessenger_ReplyMessage_Call {
	return &MockLINEMessenger_ReplyMessage_Call{Call: _e.mock.On("ReplyMessage", request)}
}

func (_c *MockLINEMessenger_ReplyMessage_Call) Run(run func(request *messaging_api.ReplyMessageRequest)) *MockLINEMessenger_ReplyMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*messaging_api.ReplyMessageRequest))
	})
	return _c
}

func (_c *MockLINEMessenger_ReplyMessage_Call) Return(_a0 *messaging_api.ReplyMessageResponse, _a1 error) *MockLINEMessenger_ReplyMessage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLINEMessenger_ReplyMessage_Call) RunAndReturn(run func(*messaging_api.ReplyMessageRequest) (*messaging_api.ReplyMessageResponse, error)) *MockLINEMessenger_ReplyMessage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLINEMessenger creates a new instance of MockLINEMessenger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLINEMessenger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLINEMessenger {
	mock := &MockLINEMessenger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
