// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/morinonusi421/cupid/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockMatcher is an autogenerated mock type for the Matcher type
type MockMatcher struct {
	mock.Mock
}

type MockMatcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMatcher) EXPECT() *MockMatcher_Expecter {
	return &MockMatcher_Expecter{mock: &_m.Mock}
}

// CheckAndUpdateMatch provides a mock function with given fields: ctx, currentUser
func (_m *MockMatcher) CheckAndUpdateMatch(ctx context.Context, currentUser *model.User) (bool, *model.User, error) {
	ret := _m.Called(ctx, currentUser)

	if len(ret) == 0 {
		panic("no return value specified for CheckAndUpdateMatch")
	}

	var r0 bool
	var r1 *model.User
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.User) (bool, *model.User, error)); ok {
		return rf(ctx, currentUser)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.User) bool); ok {
		r0 = rf(ctx, currentUser)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.User) *model.User); ok {
		r1 = rf(ctx, currentUser)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*model.User)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, *model.User) error); ok {
		r2 = rf(ctx, currentUser)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockMatcher_CheckAndUpdateMatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckAndUpdateMatch'
type MockMatcher_CheckAndUpdateMatch_Call struct {
	*mock.Call
}

// CheckAndUpdateMatch is a helper method to define mock.On call
//   - ctx context.Context
//   - currentUser *model.User
func (_e *MockMatcher_Expecter) CheckAndUpdateMatch(ctx interface{}, currentUser interface{}) *MockMatcher_CheckAndUpdateMatch_Call {
	return &MockMatcher_CheckAndUpdateMatch_Call{Call: _e.mock.On("CheckAndUpdateMatch", ctx, currentUser)}
}

func (_c *MockMatcher_CheckAndUpdateMatch_Call) Run(run func(ctx context.Context, currentUser *model.User)) *MockMatcher_CheckAndUpdateMatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.User))
	})
	return _c
}

func (_c *MockMatcher_CheckAndUpdateMatch_Call) Return(matched bool, matchedUser *model.User, err error) *MockMatcher_CheckAndUpdateMatch_Call {
	_c.Call.Return(matched, matchedUser, err)
	return _c
}

func (_c *MockMatcher_CheckAndUpdateMatch_Call) RunAndReturn(run func(context.Context, *model.User) (bool, *model.User, error)) *MockMatcher_CheckAndUpdateMatch_Call {
	_c.Call.Return(run)
	return _c
}

// UnmatchUsers provides a mock function with given fields: ctx, initiatorUserID, partnerUserID
func (_m *MockMatcher) UnmatchUsers(ctx context.Context, initiatorUserID string, partnerUserID string) (*model.User, *model.User, error) {
	ret := _m.Called(ctx, initiatorUserID, partnerUserID)

	if len(ret) == 0 {
		panic("no return value specified for UnmatchUsers")
	}

	var r0 *model.User
	var r1 *model.User
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.User, *model.User, error)); ok {
		return rf(ctx, initiatorUserID, partnerUserID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.User); ok {
		r0 = rf(ctx, initiatorUserID, partnerUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) *model.User); ok {
		r1 = rf(ctx, initiatorUserID, partnerUserID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*model.User)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = rf(ctx, initiatorUserID, partnerUserID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockMatcher_UnmatchUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnmatchUsers'
type MockMatcher_UnmatchUsers_Call struct {
	*mock.Call
}

// UnmatchUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - initiatorUserID string
//   - partnerUserID string
func (_e *MockMatcher_Expecter) UnmatchUsers(ctx interface{}, initiatorUserID interface{}, partnerUserID interface{}) *MockMatcher_UnmatchUsers_Call {
	return &MockMatcher_UnmatchUsers_Call{Call: _e.mock.On("UnmatchUsers", ctx, initiatorUserID, partnerUserID)}
}

func (_c *MockMatcher_UnmatchUsers_Call) Run(run func(ctx context.Context, initiatorUserID string, partnerUserID string)) *MockMatcher_UnmatchUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockMatcher_UnmatchUsers_Call) Return(initiatorUser *model.User, partnerUser *model.User, err error) *MockMatcher_UnmatchUsers_Call {
	_c.Call.Return(initiatorUser, partnerUser, err)
	return _c
}

func (_c *MockMatcher_UnmatchUsers_Call) RunAndReturn(run func(context.Context, string, string) (*model.User, *model.User, error)) *MockMatcher_UnmatchUsers_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMatcher creates a new instance of MockMatcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMatcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMatcher {
	mock := &MockMatcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
