// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/morinonusi421/cupid/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockMatchUserStore is an autogenerated mock type for the MatchUserStore type
type MockMatchUserStore struct {
	mock.Mock
}

type MockMatchUserStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMatchUserStore) EXPECT() *MockMatchUserStore_Expecter {
	return &MockMatchUserStore_Expecter{mock: &_m.Mock}
}

// FindByLineID provides a mock function with given fields: ctx, lineID
func (_m *MockMatchUserStore) FindByLineID(ctx context.Context, lineID string) (*model.User, error) {
	ret := _m.Called(ctx, lineID)

	if len(ret) == 0 {
		panic("no return value specified for FindByLineID")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.User, error)); ok {
		return rf(ctx, lineID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.User); ok {
		r0 = rf(ctx, lineID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, lineID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMatchUserStore_FindByLineID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByLineID'
type MockMatchUserStore_FindByLineID_Call struct {
	*mock.Call
}

// FindByLineID is a helper method to define mock.On call
//   - ctx context.Context
//   - lineID string
func (_e *MockMatchUserStore_Expecter) FindByLineID(ctx interface{}, lineID interface{}) *MockMatchUserStore_FindByLineID_Call {
	return &MockMatchUserStore_FindByLineID_Call{Call: _e.mock.On("FindByLineID", ctx, lineID)}
}

func (_c *MockMatchUserStore_FindByLineID_Call) Run(run func(ctx context.Context, lineID string)) *MockMatchUserStore_FindByLineID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMatchUserStore_FindByLineID_Call) Return(_a0 *model.User, _a1 error) *MockMatchUserStore_FindByLineID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMatchUserStore_FindByLineID_Call) RunAndReturn(run func(context.Context, string) (*model.User, error)) *MockMatchUserStore_FindByLineID_Call {
	_c.Call.Return(run)
	return _c
}

// FindMatchingUser provides a mock function with given fields: ctx, currentUser
func (_m *MockMatchUserStore) FindMatchingUser(ctx context.Context, currentUser *model.User) (*model.User, error) {
	ret := _m.Called(ctx, currentUser)

	if len(ret) == 0 {
		panic("no return value specified for FindMatchingUser")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.User) (*model.User, error)); ok {
		return rf(ctx, currentUser)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.User) *model.User); ok {
		r0 = rf(ctx, currentUser)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.User) error); ok {
		r1 = rf(ctx, currentUser)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMatchUserStore_FindMatchingUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindMatchingUser'
type MockMatchUserStore_FindMatchingUser_Call struct {
	*mock.Call
}

// FindMatchingUser is a helper method to define mock.On call
//   - ctx context.Context
//   - currentUser *model.User
func (_e *MockMatchUserStore_Expecter) FindMatchingUser(ctx interface{}, currentUser interface{}) *MockMatchUserStore_FindMatchingUser_Call {
	return &MockMatchUserStore_FindMatchingUser_Call{Call: _e.mock.On("FindMatchingUser", ctx, currentUser)}
}

func (_c *MockMatchUserStore_FindMatchingUser_Call) Run(run func(ctx context.Context, currentUser *model.User)) *MockMatchUserStore_FindMatchingUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.User))
	})
	return _c
}

func (_c *MockMatchUserStore_FindMatchingUser_Call) Return(_a0 *model.User, _a1 error) *MockMatchUserStore_FindMatchingUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMatchUserStore_FindMatchingUser_Call) RunAndReturn(run func(context.Context, *model.User) (*model.User, error)) *MockMatchUserStore_FindMatchingUser_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, user
func (_m *MockMatchUserStore) Update(ctx context.Context, user *model.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMatchUserStore_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockMatchUserStore_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - user *model.User
func (_e *MockMatchUserStore_Expecter) Update(ctx interface{}, user interface{}) *MockMatchUserStore_Update_Call {
	return &MockMatchUserStore_Update_Call{Call: _e.mock.On("Update", ctx, user)}
}

func (_c *MockMatchUserStore_Update_Call) Run(run func(ctx context.Context, user *model.User)) *MockMatchUserStore_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.User))
	})
	return _c
}

func (_c *MockMatchUserStore_Update_Call) Return(_a0 error) *MockMatchUserStore_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMatchUserStore_Update_Call) RunAndReturn(run func(context.Context, *model.User) error) *MockMatchUserStore_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMatchUserStore creates a new instance of MockMatchUserStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMatchUserStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMatchUserStore {
	mock := &MockMatchUserStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
