// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockNotifier is an autogenerated mock type for the Notifier type
type MockNotifier struct {
	mock.Mock
}

type MockNotifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotifier) EXPECT() *MockNotifier_Expecter {
	return &MockNotifier_Expecter{mock: &_m.Mock}
}

// SendCrushRegistrationComplete provides a mock function with given fields: ctx, toUserLineID, isFirstRegistration
func (_m *MockNotifier) SendCrushRegistrationComplete(ctx context.Context, toUserLineID string, isFirstRegistration bool) error {
	ret := _m.Called(ctx, toUserLineID, isFirstRegistration)

	if len(ret) == 0 {
		panic("no return value specified for SendCrushRegistrationComplete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = rf(ctx, toUserLineID, isFirstRegistration)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNotifier_SendCrushRegistrationComplete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendCrushRegistrationComplete'
type MockNotifier_SendCrushRegistrationComplete_Call struct {
	*mock.Call
}

// SendCrushRegistrationComplete is a helper method to define mock.On call
//   - ctx context.Context
//   - toUserLineID string
//   - isFirstRegistration bool
func (_e *MockNotifier_Expecter) SendCrushRegistrationComplete(ctx interface{}, toUserLineID interface{}, isFirstRegistration interface{}) *MockNotifier_SendCrushRegistrationComplete_Call {
	return &MockNotifier_SendCrushRegistrationComplete_Call{Call: _e.mock.On("SendCrushRegistrationComplete", ctx, toUserLineID, isFirstRegistration)}
}

func (_c *MockNotifier_SendCrushRegistrationComplete_Call) Run(run func(ctx context.Context, toUserLineID string, isFirstRegistration bool)) *MockNotifier_SendCrushRegistrationComplete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(bool))
	})
	return _c
}

func (_c *MockNotifier_SendCrushRegistrationComplete_Call) Return(_a0 error) *MockNotifier_SendCrushRegistrationComplete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNotifier_SendCrushRegistrationComplete_Call) RunAndReturn(run func(context.Context, string, bool) error) *MockNotifier_SendCrushRegistrationComplete_Call {
	_c.Call.Return(run)
	return _c
}

// SendCrushRegistrationPrompt provides a mock function with given fields: ctx, toUserLineID, crushLiffURL
func (_m *MockNotifier) SendCrushRegistrationPrompt(ctx context.Context, toUserLineID string, crushLiffURL string) error {
	ret := _m.Called(ctx, toUserLineID, crushLiffURL)

	if len(ret) == 0 {
		panic("no return value specified for SendCrushRegistrationPrompt")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, toUserLineID, crushLiffURL)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNotifier_SendCrushRegistrationPrompt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendCrushRegistrationPrompt'
type MockNotifier_SendCrushRegistrationPrompt_Call struct {
	*mock.Call
}

// SendCrushRegistrationPrompt is a helper method to define mock.On call
//   - ctx context.Context
//   - toUserLineID string
//   - crushLiffURL string
func (_e *MockNotifier_Expecter) SendCrushRegistrationPrompt(ctx interface{}, toUserLineID interface{}, crushLiffURL interface{}) *MockNotifier_SendCrushRegistrationPrompt_Call {
	return &MockNotifier_SendCrushRegistrationPrompt_Call{Call: _e.mock.On("SendCrushRegistrationPrompt", ctx, toUserLineID, crushLiffURL)}
}

func (_c *MockNotifier_SendCrushRegistrationPrompt_Call) Run(run func(ctx context.Context, toUserLineID string, crushLiffURL string)) *MockNotifier_SendCrushRegistrationPrompt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockNotifier_SendCrushRegistrationPrompt_Call) Return(_a0 error) *MockNotifier_SendCrushRegistrationPrompt_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNotifier_SendCrushRegistrationPrompt_Call) RunAndReturn(run func(context.Context, string, string) error) *MockNotifier_SendCrushRegistrationPrompt_Call {
	_c.Call.Return(run)
	return _c
}

// SendFollowGreeting provides a mock function with given fields: ctx, replyToken, userLiffURL
func (_m *MockNotifier) SendFollowGreeting(ctx context.Context, replyToken string, userLiffURL string) error {
	ret := _m.Called(ctx, replyToken, userLiffURL)

	if len(ret) == 0 {
		panic("no return value specified for SendFollowGreeting")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, replyToken, userLiffURL)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNotifier_SendFollowGreeting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendFollowGreeting'
type MockNotifier_SendFollowGreeting_Call struct {
	*mock.Call
}

// SendFollowGreeting is a helper method to define mock.On call
//   - ctx context.Context
//   - replyToken string
//   - userLiffURL string
func (_e *MockNotifier_Expecter) SendFollowGreeting(ctx interface{}, replyToken interface{}, userLiffURL interface{}) *MockNotifier_SendFollowGreeting_Call {
	return &MockNotifier_SendFollowGreeting_Call{Call: _e.mock.On("SendFollowGreeting", ctx, replyToken, userLiffURL)}
}

func (_c *MockNotifier_SendFollowGreeting_Call) Run(run func(ctx context.Context, replyToken string, userLiffURL string)) *MockNotifier_SendFollowGreeting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockNotifier_SendFollowGreeting_Call) Return(_a0 error) *MockNotifier_SendFollowGreeting_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNotifier_SendFollowGreeting_Call) RunAndReturn(run func(context.Context, string, string) error) *MockNotifier_SendFollowGreeting_Call {
	_c.Call.Return(run)
	return _c
}

// SendJoinGroupGreeting provides a mock function with given fields: ctx, replyToken
func (_m *MockNotifier) SendJoinGroupGreeting(ctx context.Context, replyToken string) error {
	ret := _m.Called(ctx, replyToken)

	if len(ret) == 0 {
		panic("no return value specified for SendJoinGroupGreeting")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, replyToken)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNotifier_SendJoinGroupGreeting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendJoinGroupGreeting'
type MockNotifier_SendJoinGroupGreeting_Call struct {
	*mock.Call
}

// SendJoinGroupGreeting is a helper method to define mock.On call
//   - ctx context.Context
//   - replyToken string
func (_e *MockNotifier_Expecter) SendJoinGroupGreeting(ctx interface{}, replyToken interface{}) *MockNotifier_SendJoinGroupGreeting_Call {
	return &MockNotifier_SendJoinGroupGreeting_Call{Call: _e.mock.On("SendJoinGroupGreeting", ctx, replyToken)}
}

func (_c *MockNotifier_SendJoinGroupGreeting_Call) Run(run func(ctx context.Context, replyToken string)) *MockNotifier_SendJoinGroupGreeting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockNotifier_SendJoinGroupGreeting_Call) Return(_a0 error) *MockNotifier_SendJoinGroupGreeting_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNotifier_SendJoinGroupGreeting_Call) RunAndReturn(run func(context.Context, string) error) *MockNotifier_SendJoinGroupGreeting_Call {
	_c.Call.Return(run)
	return _c
}

// SendMatchNotification provides a mock function with given fields: ctx, toUserLineID, matchedUserName
func (_m *MockNotifier) SendMatchNotification(ctx context.Context, toUserLineID string, matchedUserName string) error {
	ret := _m.Called(ctx, toUserLineID, matchedUserName)

	if len(ret) == 0 {
		panic("no return value specified for SendMatchNotification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, toUserLineID, matchedUserName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNotifier_SendMatchNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMatchNotification'
type MockNotifier_SendMatchNotification_Call struct {
	*mock.Call
}

// SendMatchNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - toUserLineID string
//   - matchedUserName string
func (_e *MockNotifier_Expecter) SendMatchNotification(ctx interface{}, toUserLineID interface{}, matchedUserName interface{}) *MockNotifier_SendMatchNotification_Call {
	return &MockNotifier_SendMatchNotification_Call{Call: _e.mock.On("SendMatchNotification", ctx, toUserLineID, matchedUserName)}
}

func (_c *MockNotifier_SendMatchNotification_Call) Run(run func(ctx context.Context, toUserLineID string, matchedUserName string)) *MockNotifier_SendMatchNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockNotifier_SendMatchNotification_Call) Return(_a0 error) *MockNotifier_SendMatchNotification_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNotifier_SendMatchNotification_Call) RunAndReturn(run func(context.Context, string, string) error) *MockNotifier_SendMatchNotification_Call {
	_c.Call.Return(run)
	return _c
}

// SendUnmatchNotification provides a mock function with given fields: ctx, toUserLineID, partnerUserName, isInitiator
func (_m *MockNotifier) SendUnmatchNotification(ctx context.Context, toUserLineID string, partnerUserName string, isInitiator bool) error {
	ret := _m.Called(ctx, toUserLineID, partnerUserName, isInitiator)

	if len(ret) == 0 {
		panic("no return value specified for SendUnmatchNotification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) error); ok {
		r0 = rf(ctx, toUserLineID, partnerUserName, isInitiator)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNotifier_SendUnmatchNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendUnmatchNotification'
type MockNotifier_SendUnmatchNotification_Call struct {
	*mock.Call
}

// SendUnmatchNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - toUserLineID string
//   - partnerUserName string
//   - isInitiator bool
func (_e *MockNotifier_Expecter) SendUnmatchNotification(ctx interface{}, toUserLineID interface{}, partnerUserName interface{}, isInitiator interface{}) *MockNotifier_SendUnmatchNotification_Call {
	return &MockNotifier_SendUnmatchNotification_Call{Call: _e.mock.On("SendUnmatchNotification", ctx, toUserLineID, partnerUserName, isInitiator)}
}

func (_c *MockNotifier_SendUnmatchNotification_Call) Run(run func(ctx context.Context, toUserLineID string, partnerUserName string, isInitiator bool)) *MockNotifier_SendUnmatchNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(bool))
	})
	return _c
}

func (_c *MockNotifier_SendUnmatchNotification_Call) Return(_a0 error) *MockNotifier_SendUnmatchNotification_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNotifier_SendUnmatchNotification_Call) RunAndReturn(run func(context.Context, string, string, bool) error) *MockNotifier_SendUnmatchNotification_Call {
	_c.Call.Return(run)
	return _c
}

// SendUserInfoUpdateConfirmation provides a mock function with given fields: ctx, toUserLineID
func (_m *MockNotifier) SendUserInfoUpdateConfirmation(ctx context.Context, toUserLineID string) error {
	ret := _m.Called(ctx, toUserLineID)

	if len(ret) == 0 {
		panic("no return value specified for SendUserInfoUpdateConfirmation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, toUserLineID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNotifier_SendUserInfoUpdateConfirmation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendUserInfoUpdateConfirmation'
type MockNotifier_SendUserInfoUpdateConfirmation_Call struct {
	*mock.Call
}

// SendUserInfoUpdateConfirmation is a helper method to define mock.On call
//   - ctx context.Context
//   - toUserLineID string
func (_e *MockNotifier_Expecter) SendUserInfoUpdateConfirmation(ctx interface{}, toUserLineID interface{}) *MockNotifier_SendUserInfoUpdateConfirmation_Call {
	return &MockNotifier_SendUserInfoUpdateConfirmation_Call{Call: _e.mock.On("SendUserInfoUpdateConfirmation", ctx, toUserLineID)}
}

func (_c *MockNotifier_SendUserInfoUpdateConfirmation_Call) Run(run func(ctx context.Context, toUserLineID string)) *MockNotifier_SendUserInfoUpdateConfirmation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockNotifier_SendUserInfoUpdateConfirmation_Call) Return(_a0 error) *MockNotifier_SendUserInfoUpdateConfirmation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNotifier_SendUserInfoUpdateConfirmation_Call) RunAndReturn(run func(context.Context, string) error) *MockNotifier_SendUserInfoUpdateConfirmation_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNotifier creates a new instance of MockNotifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotifier {
	mock := &MockNotifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
