 // Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/morinonusi421/cupid/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockUserStore is an autogenerated mock type for the UserStore type
type MockUserStore struct {
	mock.Mock
}

type MockUserStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserStore) EXPECT() *MockUserStore_Expecter {
	return &MockUserStore_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, user
func (_m *MockUserStore) Create(ctx context.Context, user *model.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - user *model.User
func (_e *MockUserStore_Expecter) Create(ctx interface{}, user interface{}) *MockUserStore_Create_Call {
	return &MockUserStore_Create_Call{Call: _e.mock.On("Create", ctx, user)}
}

func (_c *MockUserStore_Create_Call) Run(run func(ctx context.Context, user *model.User)) *MockUserStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.User))
	})
	return _c
}

func (_c *MockUserStore_Create_Call) Return(_a0 error) *MockUserStore_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserStore_Create_Call) RunAndReturn(run func(context.Context, *model.User) error) *MockUserStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByLineID provides a mock function with given fields: ctx, lineID
func (_m *MockUserStore) FindByLineID(ctx context.Context, lineID string) (*model.User, error) {
	ret := _m.Called(ctx, lineID)

	if len(ret) == 0 {
		panic("no return value specified for FindByLineID")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.User, error)); ok {
		return rf(ctx, lineID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.User); ok {
		r0 = rf(ctx, lineID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, lineID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserStore_FindByLineID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByLineID'
type MockUserStore_FindByLineID_Call struct {
	*mock.Call
}

// FindByLineID is a helper method to define mock.On call
//   - ctx context.Context
//   - lineID string
func (_e *MockUserStore_Expecter) FindByLineID(ctx interface{}, lineID interface{}) *MockUserStore_FindByLineID_Call {
	return &MockUserStore_FindByLineID_Call{Call: _e.mock.On("FindByLineID", ctx, lineID)}
}

func (_c *MockUserStore_FindByLineID_Call) Run(run func(ctx context.Context, lineID string)) *MockUserStore_FindByLineID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserStore_FindByLineID_Call) Return(_a0 *model.User, _a1 error) *MockUserStore_FindByLineID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserStore_FindByLineID_Call) RunAndReturn(run func(context.Context, string) (*model.User, error)) *MockUserStore_FindByLineID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByNameAndBirthday provides a mock function with given fields: ctx, name, birthday
func (_m *MockUserStore) FindByNameAndBirthday(ctx context.Context, name string, birthday string) (*model.User, error) {
	ret := _m.Called(ctx, name, birthday)

	if len(ret) == 0 {
		panic("no return value specified for FindByNameAndBirthday")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.User, error)); ok {
		return rf(ctx, name, birthday)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.User); ok {
		r0 = rf(ctx, name, birthday)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, name, birthday)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserStore_FindByNameAndBirthday_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByNameAndBirthday'
type MockUserStore_FindByNameAndBirthday_Call struct {
	*mock.Call
}

// FindByNameAndBirthday is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - birthday string
func (_e *MockUserStore_Expecter) FindByNameAndBirthday(ctx interface{}, name interface{}, birthday interface{}) *MockUserStore_FindByNameAndBirthday_Call {
	return &MockUserStore_FindByNameAndBirthday_Call{Call: _e.mock.On("FindByNameAndBirthday", ctx, name, birthday)}
}

func (_c *MockUserStore_FindByNameAndBirthday_Call) Run(run func(ctx context.Context, name string, birthday string)) *MockUserStore_FindByNameAndBirthday_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockUserStore_FindByNameAndBirthday_Call) Return(_a0 *model.User, _a1 error) *MockUserStore_FindByNameAndBirthday_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserStore_FindByNameAndBirthday_Call) RunAndReturn(run func(context.Context, string, string) (*model.User, error)) *MockUserStore_FindByNameAndBirthday_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, user
func (_m *MockUserStore) Update(ctx context.Context, user *model.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserStore_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUserStore_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - user *model.User
func (_e *MockUserStore_Expecter) Update(ctx interface{}, user interface{}) *MockUserStore_Update_Call {
	return &MockUserStore_Update_Call{Call: _e.mock.On("Update", ctx, user)}
}

func (_c *MockUserStore_Update_Call) Run(run func(ctx context.Context, user *model.User)) *MockUserStore_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.User))
	})
	return _c
}

func (_c *MockUserStore_Update_Call) Return(_a0 error) *MockUserStore_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserStore_Update_Call) RunAndReturn(run func(context.Context, *model.User) error) *MockUserStore_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserStore creates a new instance of MockUserStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserStore {
	mock := &MockUserStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
