// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockUserService is an autogenerated mock type for the UserService type
type MockUserService struct {
	mock.Mock
}

type MockUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserService) EXPECT() *MockUserService_Expecter {
	return &MockUserService_Expecter{mock: &_m.Mock}
}

// HandleFollowEvent provides a mock function with given fields: ctx, replyToken
func (_m *MockUserService) HandleFollowEvent(ctx context.Context, replyToken string) error {
	ret := _m.Called(ctx, replyToken)

	if len(ret) == 0 {
		panic("no return value specified for HandleFollowEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, replyToken)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserService_HandleFollowEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleFollowEvent'
type MockUserService_HandleFollowEvent_Call struct {
	*mock.Call
}

// HandleFollowEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - replyToken string
func (_e *MockUserService_Expecter) HandleFollowEvent(ctx interface{}, replyToken interface{}) *MockUserService_HandleFollowEvent_Call {
	return &MockUserService_HandleFollowEvent_Call{Call: _e.mock.On("HandleFollowEvent", ctx, replyToken)}
}

func (_c *MockUserService_HandleFollowEvent_Call) Run(run func(ctx context.Context, replyToken string)) *MockUserService_HandleFollowEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserService_HandleFollowEvent_Call) Return(_a0 error) *MockUserService_HandleFollowEvent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserService_HandleFollowEvent_Call) RunAndReturn(run func(context.Context, string) error) *MockUserService_HandleFollowEvent_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessTextMessage provides a mock function with given fields: ctx, userID
func (_m *MockUserService) ProcessTextMessage(ctx context.Context, userID string) (string, string, string, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ProcessTextMessage")
	}

	var r0 string
	var r1 string
	var r2 string
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, string, string, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) string); ok {
		r2 = rf(ctx, userID)
	} else {
		r2 = ret.Get(2).(string)
	}

	if rf, ok := ret.Get(3).(func(context.Context, string) error); ok {
		r3 = rf(ctx, userID)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// MockUserService_ProcessTextMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessTextMessage'
type MockUserService_ProcessTextMessage_Call struct {
	*mock.Call
}

// ProcessTextMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockUserService_Expecter) ProcessTextMessage(ctx interface{}, userID interface{}) *MockUserService_ProcessTextMessage_Call {
	return &MockUserService_ProcessTextMessage_Call{Call: _e.mock.On("ProcessTextMessage", ctx, userID)}
}

func (_c *MockUserService_ProcessTextMessage_Call) Run(run func(ctx context.Context, userID string)) *MockUserService_ProcessTextMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserService_ProcessTextMessage_Call) Return(replyText string, quickReplyURL string, quickReplyLabel string, err error) *MockUserService_ProcessTextMessage_Call {
	_c.Call.Return(replyText, quickReplyURL, quickReplyLabel, err)
	return _c
}

func (_c *MockUserService_ProcessTextMessage_Call) RunAndReturn(run func(context.Context, string) (string, string, string, error)) *MockUserService_ProcessTextMessage_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterCrush provides a mock function with given fields: ctx, userID, crushName, crushBirthday, confirmUnmatch
func (_m *MockUserService) RegisterCrush(ctx context.Context, userID string, crushName string, crushBirthday string, confirmUnmatch bool) (bool, string, bool, error) {
	ret := _m.Called(ctx, userID, crushName, crushBirthday, confirmUnmatch)

	if len(ret) == 0 {
		panic("no return value specified for RegisterCrush")
	}

	var r0 bool
	var r1 string
	var r2 bool
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, bool) (bool, string, bool, error)); ok {
		return rf(ctx, userID, crushName, crushBirthday, confirmUnmatch)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, bool) bool); ok {
		r0 = rf(ctx, userID, crushName, crushBirthday, confirmUnmatch)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, bool) string); ok {
		r1 = rf(ctx, userID, crushName, crushBirthday, confirmUnmatch)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, string, bool) bool); ok {
		r2 = rf(ctx, userID, crushName, crushBirthday, confirmUnmatch)
	} else {
		r2 = ret.Get(2).(bool)
	}

	if rf, ok := ret.Get(3).(func(context.Context, string, string, string, bool) error); ok {
		r3 = rf(ctx, userID, crushName, crushBirthday, confirmUnmatch)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// MockUserService_RegisterCrush_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterCrush'
type MockUserService_RegisterCrush_Call struct {
	*mock.Call
}

// RegisterCrush is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - crushName string
//   - crushBirthday string
//   - confirmUnmatch bool
func (_e *MockUserService_Expecter) RegisterCrush(ctx interface{}, userID interface{}, crushName interface{}, crushBirthday interface{}, confirmUnmatch interface{}) *MockUserService_RegisterCrush_Call {
	return &MockUserService_RegisterCrush_Call{Call: _e.mock.On("RegisterCrush", ctx, userID, crushName, crushBirthday, confirmUnmatch)}
}

func (_c *MockUserService_RegisterCrush_Call) Run(run func(ctx context.Context, userID string, crushName string, crushBirthday string, confirmUnmatch bool)) *MockUserService_RegisterCrush_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(bool))
	})
	return _c
}

func (_c *MockUserService_RegisterCrush_Call) Return(matched bool, matchedUserName string, isFirstCrushRegistration bool, err error) *MockUserService_RegisterCrush_Call {
	_c.Call.Return(matched, matchedUserName, isFirstCrushRegistration, err)
	return _c
}

func (_c *MockUserService_RegisterCrush_Call) RunAndReturn(run func(context.Context, string, string, string, bool) (bool, string, bool, error)) *MockUserService_RegisterCrush_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterUser provides a mock function with given fields: ctx, userID, name, birthday, confirmUnmatch
func (_m *MockUserService) RegisterUser(ctx context.Context, userID string, name string, birthday string, confirmUnmatch bool) (bool, error) {
	ret := _m.Called(ctx, userID, name, birthday, confirmUnmatch)

	if len(ret) == 0 {
		panic("no return value specified for RegisterUser")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, bool) (bool, error)); ok {
		return rf(ctx, userID, name, birthday, confirmUnmatch)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, bool) bool); ok {
		r0 = rf(ctx, userID, name, birthday, confirmUnmatch)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, bool) error); ok {
		r1 = rf(ctx, userID, name, birthday, confirmUnmatch)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_RegisterUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterUser'
type MockUserService_RegisterUser_Call struct {
	*mock.Call
}

// RegisterUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - name string
//   - birthday string
//   - confirmUnmatch bool
func (_e *MockUserService_Expecter) RegisterUser(ctx interface{}, userID interface{}, name interface{}, birthday interface{}, confirmUnmatch interface{}) *MockUserService_RegisterUser_Call {
	return &MockUserService_RegisterUser_Call{Call: _e.mock.On("RegisterUser", ctx, userID, name, birthday, confirmUnmatch)}
}

func (_c *MockUserService_RegisterUser_Call) Run(run func(ctx context.Context, userID string, name string, birthday string, confirmUnmatch bool)) *MockUserService_RegisterUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(bool))
	})
	return _c
}

func (_c *MockUserService_RegisterUser_Call) Return(isFirstRegistration bool, err error) *MockUserService_RegisterUser_Call {
	_c.Call.Return(isFirstRegistration, err)
	return _c
}

func (_c *MockUserService_RegisterUser_Call) RunAndReturn(run func(context.Context, string, string, string, bool) (bool, error)) *MockUserService_RegisterUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserService creates a new instance of MockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserService {
	mock := &MockUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
