// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockIDTokenVerifier is an autogenerated mock type for the IDTokenVerifier type
type MockIDTokenVerifier struct {
	mock.Mock
}

type MockIDTokenVerifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIDTokenVerifier) EXPECT() *MockIDTokenVerifier_Expecter {
	return &MockIDTokenVerifier_Expecter{mock: &_m.Mock}
}

// VerifyIDToken provides a mock function with given fields: idToken
func (_m *MockIDTokenVerifier) VerifyIDToken(idToken string) (string, error) {
	ret := _m.Called(idToken)

	if len(ret) == 0 {
		panic("no return value specified for VerifyIDToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(idToken)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(idToken)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(idToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIDTokenVerifier_VerifyIDToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyIDToken'
type MockIDTokenVerifier_VerifyIDToken_Call struct {
	*mock.Call
}

// VerifyIDToken is a helper method to define mock.On call
//   - idToken string
func (_e *MockIDTokenVerifier_Expecter) VerifyIDToken(idToken interface{}) *MockIDTokenVerifier_VerifyIDToken_Call {
	return &MockIDTokenVerifier_VerifyIDToken_Call{Call: _e.mock.On("VerifyIDToken", idToken)}
}

func (_c *MockIDTokenVerifier_VerifyIDToken_Call) Run(run func(idToken string)) *MockIDTokenVerifier_VerifyIDToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIDTokenVerifier_VerifyIDToken_Call) Return(_a0 string, _a1 error) *MockIDTokenVerifier_VerifyIDToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIDTokenVerifier_VerifyIDToken_Call) RunAndReturn(run func(string) (string, error)) *MockIDTokenVerifier_VerifyIDToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIDTokenVerifier creates a new instance of MockIDTokenVerifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIDTokenVerifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIDTokenVerifier {
	mock := &MockIDTokenVerifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
